publisher_scaled_joint_trajectory_controller:
  ros__parameters:

    controller_name: "scaled_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [-1.76, -2.129, -1.117, -1.483, 1.57, 0.1745]
    pos2: [-1.76, -2.3911, -1.448, -0.8726, 1.57, 0.17]
    pos3: [-1.76, -2.129, -1.117, -1.483, 1.57, 0.1745]
    pos4: [-1.76, -2.3911, -1.448, -0.8726, 1.57, 0.17]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      shoulder_pan_joint: [-3.14,3.14]
      shoulder_lift_joint: [-3.14,3.14]
      elbow_joint: [-3.14,3.14]
      wrist_1_joint: [-3.14,3.14]
      wrist_2_joint: [-3.14,3.14]
      wrist_3_joint: [-3.14,3.14]

publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1: [-1.76, -2.129, -1.117, -1.483, 1.57, 0.1745]
    pos2: [-1.76, -2.3911, -1.448, -0.8726, 1.57, 0.17]
    pos3: [-1.76, -2.129, -1.117, -1.483, 1.57, 0.1745]
    pos4: [-1.76, -2.3911, -1.448, -0.8726, 1.57, 0.17]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: true
    starting_point_limits:
      shoulder_pan_joint: [-3.14,3.14]
      shoulder_lift_joint: [-3.14,3.14]
      elbow_joint: [-3.14,3.14]
      wrist_1_joint: [-3.14,3.14]
      wrist_2_joint: [-3.14,3.14]
      wrist_3_joint: [-3.14,3.14]
